#              __  __          __  __                  __  ______                  __
#             /\ \/\ \        /\ \/\ \          __    /\ \/\__  _\                /\ \
#             \ \ `\\ \    ___\ \ \ \ \    ___ /\_\   \_\ \/_/\ \/ _ __    __     \_\ \     __    ____
#              \ \ , ` \  / __`\ \ \ \ \  / __`\/\ \  /'_` \ \ \ \/\`'__\/'__`\   /'_` \  /'__`\ /',__\
#               \ \ \`\ \/\ \L\ \ \ \_/ \/\ \L\ \ \ \/\ \L\ \ \ \ \ \ \//\ \L\.\_/\ \L\ \/\  __//\__, `\
#                \ \_\ \_\ \____/\ `\___/\ \____/\ \_\ \___,_\ \ \_\ \_\\ \__/.\_\ \___,_\ \____\/\____/
#                 \/_/\/_/\/___/  `\/__/  \/___/  \/_/\/__,_ /  \/_/\/_/ \/__/\/_/\/__,_ /\/____/\/___/
#                                                   ____________
#                                                   by HIlight3R

config:
  ticks-after-moving: 1 # Amount of ticks after moving to get access to the trading window
  max-distance: 5.0 # Maximum distance between a player and a villager after which the trading window will be closed